#spring.application.name=Identity Reconciliation

spring:
  application:
    name: logistiq-masters
  datasource:
    password: ${DB_PASSWORD:jhggh}
    url: ${DB_URL:jdbc:postgresql://localhost:5434/masters}
    username: ${DB_USERNAME:postgres}
  flyway:
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
